### ISSUE TITLE
Add Github Greetings Bot

### ISSUE THREAD

**Issue by KiranBaliga** [subhadeeproy3902/trailgo#1]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24 Ext )

**Comment by subhadeeproy3902** [comment]
Umm not needed ! @KiranBaliga
