### ISSUE TITLE
Implementation of Serviecs Page | Currently Services page is Blank, Want to implement that

### ISSUE THREAD

**Issue by Shariq2003** [subhadeeproy3902/trailgo#106]
![image](https://github.com/user-attachments/assets/be5807ef-5530-48d4-8039-47b862947c63)

Currently Services page is Blank, Want to implement that page as a result the UI and UX will be enhanced.

@subhadeeproy3902 sir, please assign this to me,

**Comment by subhadeeproy3902** [comment]
Not needed !
