### ISSUE TITLE
Implementation of Pricing Page | Will Contain Premium Plans | Currently No Pricing page is there in the website

### ISSUE THREAD

**Issue by Shariq2003** [subhadeeproy3902/trailgo#107]
![image](https://github.com/user-attachments/assets/566fd0ec-d33a-4e48-b4b4-4bf7ecaadcce)

Currently No Pricing page is there in the website, I want to add a pricing page that will contains the premium offers, etc.

**Comment by subhadeeproy3902** [comment]
Not needed !
