### ISSUE TITLE
Enhancement of Login and SIgnUp Page

### ISSUE THREAD

**Issue by Shariq2003** [subhadeeproy3902/trailgo#109]
![image](https://github.com/user-attachments/assets/8609314d-9cfe-4dad-9e0e-0a58eb3e13ce)

![image](https://github.com/user-attachments/assets/72eced26-4656-4b1f-a35a-76c35afbd995)

The Logina and SignUp pages are not attractive at all, no framer motion animation, not an attractive UI and not a better UX.

I want to redesign the Login and SignUp page.

@subhadeeproy3902 sir, could u please assign this to me.

**Comment by subhadeeproy3902** [comment]
Its looks clean and perfect to me and framer motion is not suitable in sign up or other pages ... If u wanna build UI UX then try for Hero sections, About Page, etc.
