### ISSUE TITLE
Google Auth not working on Login page

### ISSUE THREAD

**Issue by Ahsankhalid618** [subhadeeproy3902/trailgo#110]
**Google auth signIn is not working on the login page but only on the signup page, No functionality has been added to Google auth on the login page.**

https://github.com/user-attachments/assets/e1a1d711-86a9-4f63-9ef4-5a1cfc3cfd37

### Assign me this issue under gssoc-ext, level3 and hacktoberfest. Thanks. 💫

**Comment by subhadeeproy3902** [comment]
Ok cool u can do it !

**Comment by Ahsankhalid618** [comment]
@subhadeeproy3902 yeah i am doing it, kindly change the label of level1 to level3, It's a complete authentication process. Thanks
