### ISSUE TITLE
Add a fully responsive our services with reference to the canva ppt provided for project

### ISSUE THREAD

**Issue by ShivanshPlays** [subhadeeproy3902/trailgo#124]
currently the services page is not available, under this issues i will make a fully responsive services page while taking the canva ppt provided under consideration while developing the page. 

![image](https://github.com/user-attachments/assets/52245e1a-3978-42d5-a99b-5d81c5860478)

**Comment by subhadeeproy3902** [comment]
focusing on the pinned issues ! @ShivanshPlays
