### ISSUE TITLE
Make a services Page according to the features described in the Canva PPT

### ISSUE THREAD

**Issue by inkerton** [subhadeeproy3902/trailgo#125]
![image](https://github.com/user-attachments/assets/4ddb2092-582d-4a90-81f7-2067d3dd90fb)

The services page will include a concluded services details that trailgo will provide .
I would like to work on it .
Please assign this to me.

**Comment by subhadeeproy3902** [comment]
alryt, I need a nice UI btw

**Comment by inkerton** [comment]
https://github.com/user-attachments/assets/2a9c92e8-89e9-4c49-80e3-c67063076cac

@subhadeeproy3902 Let me know if this is ok and You want any changes I made 3 sections for All three passengers, ticket managers and admin services then an overview .

**Comment by inkerton** [comment]
@subhadeeproy3902 

This is the services Page I made I made different components.
