### ISSUE TITLE
UI improvements: Implementing DARK/LIGHT MODE for devices

### ISSUE THREAD

**Issue by Sourabh782** [subhadeeproy3902/trailgo#127]
Dark mode is easier on the eyes, especially in low-light conditions. It reduces the amount of light emitted by device screens, which can help decrease eye fatigue and strain.
For users who are browsing in a dark environment, a dark mode interface can make text easier to read and prevent discomfort caused by bright screens.

thus adding a dark light mode switch is a good option

**Comment by subhadeeproy3902** [comment]
no need !
