### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by KiranBaliga** [subhadeeproy3902/trailgo#2]
I would like to add a code of conduct developed for your repository. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext Labels

**Comment by subhadeeproy3902** [comment]
Go ahead ! @KiranBaliga

**Comment by KiranBaliga** [comment]
@subhadeeproy3902 Please review the PR and action accordingly. Thank you! 

Please add the labels to the linked PR as well. Thanks.
