### ISSUE TITLE
Backend Connectivity

### ISSUE THREAD

**Issue by AnanyaSinha16** [subhadeeproy3902/trailgo#20]
![image](https://github.com/user-attachments/assets/9f2f7a0a-4147-4fc4-876d-5f9aac856f54)
Here, except for the register and login, none of the navigation items or menus are working. I can fix that problem .

**Comment by subhadeeproy3902** [comment]
As of now the functional requirements are reqd as priority !
Check for the pinned issues @AnanyaSinha16
