### ISSUE TITLE
Complete the signup and login process

### ISSUE THREAD

**Issue by manya1632** [subhadeeproy3902/trailgo#3]
I want to complete the whole signup and login process by authentication from google or github account. You can suggest more options you want to implement to make it a smooth process.

Checklist
 I have checked the existing issues.
 I have read the Contributing Guidelines
 I have read the Code Of Conduct
 The changes don't break the code

I hope you assign this issue to me. I got ideas and feel free to suggest new ones!

**Comment by manya1632** [comment]
Sir, there will be some delay in completing this task due to my exams. So, I am expecting a delay of about 8 days . I want to do this task but if there's any urgency feel free to assign this task to someone else. 
Thank you.

**Comment by Swetabh333** [comment]
@subhadeeproy3902  I'd like to work on this.

**Comment by SuyashSingh01** [comment]
Hi @subhadeeproy3902  I'm excited to contribute  .please assign this issue to me .

**Comment by aasiflm10** [comment]
If this issue is still open i would like to work on this issue @subhadeeproy3902

**Comment by subhadeeproy3902** [comment]
Its already done !
Click on "Register"
