### ISSUE TITLE
Contributing doc

### ISSUE THREAD

**Issue by saumyayadav25** [subhadeeproy3902/trailgo#30]
Your contrubuting.md is well structured and nicely explained.

### how to contribute 
this heading has guidelines on how to contribute but for those who will be contributing for first time, they might not know
- how to fork the repo
- how and where to create branch?
- how to push their changes to github

I can add relevant screenshots and terminal command lines for those who are contributing for first time and make it easy to understand the flow of contributing in your project.

Do let me know if the issue is assigned to me

**Comment by subhadeeproy3902** [comment]
@saumyayadav25 Already there
