### ISSUE TITLE
adding contact us page.

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [subhadeeproy3902/trailgo#33]
there is no contact page  , @subhadeeproy3902 if u assign me this task i would love to create a contact us page.
<img width="125" alt="Screenshot 2024-10-13 at 7 20 31 PM" src="https://github.com/user-attachments/assets/0d8937be-7127-4bd9-abbf-6ba95481c709">

**Comment by subhadeeproy3902** [comment]
Already an raised Issue @T-Rahul-prabhu-38
