### ISSUE TITLE
crearing 3 pages sections for home page.

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [subhadeeproy3902/trailgo#35]
@subhadeeproy3902 can you assign me so i can work on creating these 3 pages.

<img width="268" alt="Screenshot 2024-10-13 at 7 22 35 PM" src="https://github.com/user-attachments/assets/ba4bdd6f-282d-4111-ae55-2b69d620aab9">

**Comment by subhadeeproy3902** [comment]
Already in progress @T-Rahul-prabhu-38
