### ISSUE TITLE
Add Login with Password Functionality

### ISSUE THREAD

**Issue by saras-69** [subhadeeproy3902/trailgo#40]
Description:
Implement a login feature that allows users to authenticate using their email and password. This feature will ensure users can securely access their accounts.

Tasks:

Create a login form with email and password fields.
Validate input fields (e.g., valid email format, minimum password length).
Display error messages for invalid credentials.
Implement password masking and a "show/hide password" option.
Store login state (e.g., using localStorage or session management).
Redirect users to the appropriate page after a successful login.
Provide meaningful feedback (e.g., success message, loading indicator).

**Comment by subhadeeproy3902** [comment]
No Need .. Check for pinned issues

**Comment by saras-69** [comment]
Hey @subhadeeproy3902  but you mentioned in functional requirements

**Comment by saras-69** [comment]
> No Need .. Check for pinned issues



> No Need .. Check for pinned issues

Hey @subhadeeproy3902 Thank you for your guidance regarding the pinned issues. I wanted to highlight that the Password Recovery Feature aligns closely with several functional requirements related to user account management, specifically:

Secure login and authentication: Integrating a password recovery feature enhances security by allowing users to reset their passwords securely.
Profile management: Users can manage their profiles effectively with the ability to recover their accounts.

I believe implementing this feature will improve user experience significantly. If there’s an existing pinned issue that addresses this, I would appreciate your guidance in linking my issue to it.
