### ISSUE TITLE
Make it Responsive for Mobile layout and add Footer

### ISSUE THREAD

**Issue by Jainpaswan** [subhadeeproy3902/trailgo#42]
UI is not working for mobile layout screens .
@subhadeeproy3902  I will recommend you to assign this to me 
i will add footer and make it responsive for mobile layout too using tailwindcss
Please add the label on this issue and assign this to me
for gssco ,hacktoberfest
![Screenshot 2024-10-14 013554](https://github.com/user-attachments/assets/b37e26f2-d569-4d11-b7e7-4fd19d07abc8)
![Screenshot 2024-10-14 013606](https://github.com/user-attachments/assets/a086553d-b10d-47ea-831a-50a7b8d74deb)

**Comment by subhadeeproy3902** [comment]
already a raised issue @Jainpaswan
