### ISSUE TITLE
COPYRIGHTS SECTION AT THE BOTTOM OF THE PAGE IS MISSING.

### ISSUE THREAD

**Issue by ABHISIKTAcommits** [subhadeeproy3902/trailgo#48]
A COPYRIGHT SECTION IS NEEDED TO BE ADDED AT THE BOTTOM OF THE SCREEN FOR SECURITY REASONS.
PLEASE ASSIGN THIS ISSUE TO ME AND ALSO ADD THE LABELS OF hacktoberfest-accepted and gssoc-extd.

Adding the section would make the page more professional.

**Comment by subhadeeproy3902** [comment]
![Uploading image.png…]()
