### ISSUE TITLE
THE NAME OF THE WEBSITE THAT IS "trailgo" IS MISSING BESIDE THE LOGO IN THE NAVBAR.

### ISSUE THREAD

**Issue by ABHISIKTAcommits** [subhadeeproy3902/trailgo#49]
I WANT TO WORK ON THIS. ADDING THE NAME OF THE WEBSITE ON THE NAVBAR BESIDE THE ICON WOULD MAKE IT LOOK GOOD.
PREVIEW :

![Screenshot 2024-10-15 133036](https://github.com/user-attachments/assets/dce05f54-4c13-43c6-a51d-4c39dc7cc66d)

PLEASE ASSIGN THIS ISSUE TO ME AND ALSO ADD THE LABELS OF hacktoberfest-accepted and gssoc-extd.

**Comment by subhadeeproy3902** [comment]
Not focused on these bro, Check for the pinned issues !
