### ISSUE TITLE
Add FAQ Section

### ISSUE THREAD

**Issue by rudrapratap63** [subhadeeproy3902/trailgo#54]
**Description :-**
We need to implement a Frequently Asked Questions (FAQ) section for the Online Railway Commodity Reservation System, Trailgo. This section will help users quickly find answers to common queries, enhancing their experience with the platform.

**Benefits:-**
1.Reduces the need for customer support inquiries.
2.Provides users with instant access to important information.
3.Enhances the overall user experience on the platform.

@subhadeeproy3902, I will add questions and answers based on your Canva presentation for reference.

**Comment by subhadeeproy3902** [comment]
not focused on these... only the pinned issues... (any of the listed point in them)
