### ISSUE TITLE
Design 404 error custom page

### ISSUE THREAD

**Issue by dev129** [subhadeeproy3902/trailgo#56]
#### Description
The current 404 error page does not provide an optimal user experience, especially in a production environment. A well-designed custom 404 page can enhance the overall aesthetic and usability of the site.

#### Proposed Solution
I propose to design a custom 404 error page that aligns with the site's branding and improves user engagement. 

#### Plan
1. **Labeling**: Please assign the issue the GSSOC-ext and Hacktoberfest and level labels.
2. **Wireframe**: I will share a wireframe within the first hour of being assigned to the issue.
3. **Approval**: Upon receiving approval for the wireframe, I will start the design process.
4. **Completion**: The design will be completed within 24 hours of wireframe approval.

#### Benefits
- Improved user experience and site navigation.
- Enhanced branding consistency.
- Potential reduction in bounce rates.

I look forward to your feedback and hope to contribute positively to the project!

**Comment by subhadeeproy3902** [comment]
@dev129 Make a cool 404 page ! with a nice UI

**Comment by dev129** [comment]
![image](https://github.com/user-attachments/assets/bda9a8bc-666a-4f1c-af31-8980a491ab44)
This is a wireframe where the navbar will be taken from your site and the rest shall be designed with a go back button, let me know if you have any other design in mind so that after this i can start designing @subhadeeproy3902

**Comment by dev129** [comment]
Are you up @subhadeeproy3902 ?

**Comment by dev129** [comment]
Hello @subhadeeproy3902 @KiranBaliga @sezallagwal @Amulya-B28 can someone atleast tell me shall I start designing it or not ? I have been waiting whole day foe approval.

**Comment by dev129** [comment]
@subhadeeproy3902 should i design or not ?

**Comment by subhadeeproy3902** [comment]
isnt the UI a bit simple?

**Comment by subhadeeproy3902** [comment]
> Hello @subhadeeproy3902 @KiranBaliga @sezallagwal @Amulya-B28 can someone atleast tell me shall I start designing it or not ? I have been waiting whole day foe approval.

Bro i am also at work. You gotta keep a bit of patience

**Comment by subhadeeproy3902** [comment]
take some inspiration like
https://dribbble.com/shots/16077553-404-Error-Page-with-3D-and-Animation

Also make a designer UI in light theme for railways only if u can

**Comment by dev129** [comment]
![image](https://github.com/user-attachments/assets/35138ef7-7135-4a4d-b1cf-2f6dda47df9d)
This is just a wireframe also the UI is simple because I am just a begineer in nextJS, in case if you are thinking about using three js then it is something complicated for me, I am only familiar with basic css animation and framer-motion and worked with 2D websited only.

**Comment by subhadeeproy3902** [comment]
@dev129 Lol. u just had to wait 1 day to get a reply XD. I had wait 1 week to get a Issue assigned in an actual open source contribution so please dont talk about patience. and the wireframe u provided still is looking dull to me. So now UI of that type is not acceptable

**Comment by dev129** [comment]
@subhadeeproy3902 I am a beginner in OSS, so its a start for me and since you were not replying atleast I must have known are you even interested or not.
As for the UI , if you don't like , its fine, I think we don't always get what we want. You can close the issue if you wish to or help me out create one for you.
