### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by prasoonk1204** [subhadeeproy3902/trailgo#6]
there is no footer. I would like to add one
please assign it to me so that i can start working on that

also add _gssoc-ext, hactoberfest-accepted_ and _level (1/2/3_ -- based on what you think is the difficulty of this task) labels.

**Comment by iamsohelx** [comment]
Hii @subhadeeproy3902 could you please assign this task to me, i can help you to build a perfect footer for your website, which matches your theme

**Comment by subhadeeproy3902** [comment]
Ig assigned !

**Comment by prasoonk1204** [comment]
Don't you think you should assign issues to people who raised them first?
