### ISSUE TITLE
Add contributors in README.md

### ISSUE THREAD

**Issue by Annapoornaaradhya** [subhadeeproy3902/trailgo#62]
I would like to add contributors images to the readme file.
It looks something like this
![image](https://github.com/user-attachments/assets/dd86eb32-5793-4b9a-a4d8-e2f560eac353)

This feature is important to celebrate our contributors for their efforts.
@subhadeeproy3902 please assign me this issue.

**Comment by Annapoornaaradhya** [comment]
@subhadeeproy3902 assign me this issue under hacktoberfest-accecpted and gssoc-ext with level

**Comment by subhadeeproy3902** [comment]
Not required . currently focused on the pinned issues
