### ISSUE TITLE
Update README for better appearances

### ISSUE THREAD

**Issue by akhandpratap18** [subhadeeproy3902/trailgo#7]
Hii, your readme file looks very monotonous and doesnt invite more contributors. I can fix it by making it more attractive. I have recently made a level-2 contribution by editing readme

**Comment by akhandpratap18** [comment]
@subhadeeproy3902 assign me this

**Comment by subhadeeproy3902** [comment]
Not needed as of now @akhandpratap18 Check for the pinned issue !
