### ISSUE TITLE
the header (navbar) is also scrolling while the website is scrolled.

### ISSUE THREAD

**Issue by vidhi-github** [subhadeeproy3902/trailgo#71]
the header (navbar) is also scrolling while the website is scrolled. I want to make it sticky. Further a footer can be added to the website. i would like to address this up. kindly assign this issue to me under gssoc-ext and hacktoberfest under good level issue.
thank you

**Comment by subhadeeproy3902** [comment]
not focused on these... focusing on the pinned ones
