### ISSUE TITLE
Implement a Customized Scrollbar for Enhanced UI

### ISSUE THREAD

**Issue by RanitDERIA** [subhadeeproy3902/trailgo#73]
**Description:**
The current scrollbar in the Online Railway Commodity Reservation System (Trailgo) lacks a polished, consistent design that aligns with the overall UI aesthetics. Introducing a customized, smooth, and visually appealing scrollbar will enhance the user interface and provide a better user experience across the platform.

**Proposed Solution:**
1. Design a sleek, modern scrollbar with subtle colors and smooth scrolling effects.
2. Ensure the scrollbar is consistent across different browsers and devices.
3. Implement hover effects and animations to provide a more engaging interaction for users.

**Why I'm Suitable for This Task:**
With my background in UI/UX design and front-end development, I can ensure the scrollbar design complements the overall theme of the application. My previous contributions to GSSoC and open-source projects demonstrate my ability to enhance user interfaces and deliver clean, functional, and aesthetically pleasing components.

**Tags:**
- `enhancement`
- `ui/ux`
- `visual-design`

**Labels Request:**
Please add the following labels to this issue:
- `gssoc-ext`
- `hacktoberfest-accepted`
- `level1`

**Request:**
Please assign this issue to me for implementation. I'll make sure to introduce a stylish and user-friendly scrollbar that improves the overall browsing experience.

**Comment by subhadeeproy3902** [comment]
Not required. Focusing on the pinned issues currently
