### ISSUE TITLE
Updation of code_of_conduct file

### ISSUE THREAD

**Issue by Nikhil0-3** [subhadeeproy3902/trailgo#77]
wanted to do following changes : 

Welcome Section:
Add a line on open-source community commitment.

Our Pledge:
Include a sentence about continuous improvement.

Our Standards:
Add "Mentorship" under Positive Behavior.
Add "Doxing" under Unacceptable Behavior.

Project Goals:
Specify a Sustainability Goal.

Also , By adding symbols it looks more creative.

**Comment by Nikhil0-3** [comment]
Please assign this work to me.

**Comment by subhadeeproy3902** [comment]
Not focused on these ... Focusing on the pinned issues ! @Nikhil0-3
