### ISSUE TITLE
New Page Addition | FAQs and Forum Page | User Can Also Post

### ISSUE THREAD

**Issue by Shariq2003** [subhadeeproy3902/trailgo#80]
I want to implement the FAQs and Forums Page with Following Functionalities:-

1. Add a new FAQs Forums Page.
2. FAQs section with Listing of FAQs on Trailgo.
3. Forum Section with Listing of User's Posts in a Grid of Cards with Flip Effect on Cards.
4. User can also Post.
5. Sorting Functionality.
6. Responsive UI.

Please assign this to me under GSSOC Ext.

**Comment by Shariq2003** [comment]
@subhadeeproy3902 sir, could u please assign this to me.

**Comment by subhadeeproy3902** [comment]
Alryt!

**Comment by Shariq2003** [comment]
> Alryt!

Thanks sir 😊, for assigning, will raise the PR maybe by 1AM.
