### ISSUE TITLE
UI UX Enhancements | Addition of ProgressBar | That will represent the Current Depth of the Webpage

### ISSUE THREAD

**Issue by Shariq2003** [subhadeeproy3902/trailgo#81]
I want to add a progress bar that will show the current depth of the webpage, just like GSSOC website

![image](https://github.com/user-attachments/assets/057676e2-0bab-4a96-8137-fccaa16eb6d6)

Look at the top, an orange line

**Comment by Shariq2003** [comment]
@subhadeeproy3902  sir, could u please assign this to me.

**Comment by subhadeeproy3902** [comment]
Not needed
