### ISSUE TITLE
ADD progress bar to the landing page 

### ISSUE THREAD

**Issue by shubhagarwal1** [subhadeeproy3902/trailgo#83]
Enhances User Experience: Provides visual feedback, keeping users informed about the status of loading or ongoing tasks.
Reduces Perceived Wait Time: A progress bar gives users a sense of progress, making long wait times feel shorter and more manageable.
Increases User Engagement: By showing clear progression, it keeps users engaged and reassures them that the process is actively moving forward.

**Comment by subhadeeproy3902** [comment]
Not needed
