### ISSUE TITLE
BUG -> Data sending by GET request

### ISSUE THREAD

**Issue by Gauravtb2253** [subhadeeproy3902/trailgo#90]
Hello
Currently in the login page, the email id is sent to the backend through GET request and it is visible in the url
The form data should be sent through a POST request
I would like to fix it

![image](https://github.com/user-attachments/assets/b502cfb8-0b99-452c-bd42-083a877d7d31)

**Comment by subhadeeproy3902** [comment]
I will look that part !

**Comment by Gauravtb2253** [comment]
do you have any issue that I can solve
